- name: Import variables specific to distribution
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/default.yml"

- name: Install {{ krb5_packages }}
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ krb5_packages }}"

- name: Install - Backup krb5.conf
  ipafstore:
    backup: "{{ krb5_conf }}"

- name: Template krb5.conf
  template:
    src: krb5.conf.j2
    dest: "{{ krb5_conf }}"
    backup: no
    owner: root
    group: root
    mode: 0644
    force: yes
